# Generated by Django 3.1.4 on 2020-12-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('blogs', '0003_auto_20201211_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.ManyToManyField(related_name='categories', to='categories.Category'),
        ),
    ]
