export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const START_FETCHING_USER = "START_FETCHING_USER";
export const SET_USER_FAILED = "SET_USER_FAILED";
export const ADD_BLOG_TO_AUTH = "ADD_BLOG_TO_AUTH";
